services:
  db:
    image: postgres
    restart: always
    container_name: "unlockway_db"
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: unlockway_db
    ports:
      - 5432:5432
    volumes:
      - ./scripts/populate_ingredients.sql:/docker-entrypoint-initdb.d/init.sql:Z
      # - unlockway_db_volume:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: "unlockway_db_dashboard"
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

# volumes:
  # unlockway_db_volume: {}